databases:
 - name: stapp
   databaseName: stapp_production
   user: stapp

services:
- type: worker
   name: sidekiq
   env: ruby
   buildCommand: "bundle install"
   startCommand: "bundle exec sidekiq -q default -q mailers -C config/sidekiq.yml"
   envVars:
     - key: REDIS_URL
         value: "redis://redis-4r66:10000"

 - type: web
   name: stapp
   env: ruby
   buildCommand: "./bin/render-build.sh"
   startCommand: "bundle exec puma -C config/puma.rb"
   envVars:
     - key: DATABASE_URL
       fromDatabase:
         name: stapp
         property: connectionString
     - key: RAILS_MASTER_KEY
       sync: false
     - key: REDIS_URL
         value: "redis://redis-4r66:10000"