:verbose: false
:concurrency: 6

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 8

# You can override concurrency based on environment.
production:
  :concurrency: 6
  :queues:
  - default
staging:
  :concurrency: 3